#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Day4.Droid.Resource", IsApplication=true)]

namespace Day4.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int hyperspace = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int asteroid01 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int asteroid02 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int asteroid03 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int asteroid04 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int asteroid05 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int asteroid06 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int spinning_asteroid = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070004
			public const int btnFirst = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int button1 = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int button2 = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int imageView1 = 2131165185;
			
			// aapt resource value: 0x7f070008
			public const int txtDP = 2131165192;
			
			// aapt resource value: 0x7f070003
			public const int txtFirst = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int txtIN = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int txtPT = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int txtPX = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int txtSP = 2131165193;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_imageandbutton = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int layouttest = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int RelativeLayoutExample = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Uof = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int title_animationdrawable = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int title_spinasteroid = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int mystyle = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
