#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AndroidFlyout.Resource", IsApplication=true)]

namespace AndroidFlyout
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int drawer_shadow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_sessions = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_speakers = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_whats_on = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_drawer = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_launcher = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_tab_my_schedule_selected = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_tab_my_schedule_unselected = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_tab_sessions_selected = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_tab_sessions_unselected = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_tab_speakers_selected = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_tab_speakers_unselected = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_tab_whats_on_selected = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_tab_whats_on_unselected = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int aboutwebview = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int companyNameTextView = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int content_frame = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int drawer_layout = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int flyout = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int headshotImageView = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int locationTextView = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int sessionTitleTextView = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int speakerNameTextView = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int titles_fragment = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int twitterTextView = 2131034120;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int about = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int drawer_list_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int session_screen = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int speaker_row = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int speaker_screen = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int speakers_screen = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int drawer_close = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int drawer_open = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
