// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using CoreGraphics;

namespace TableViewDemo
{
	public partial class testTableViewController : UITableViewController
	{
		string[] names = { "Moe", "Curly", "Larry", "Shemp" };

		public testTableViewController (IntPtr handle) : base (handle)
		{
			
		}

		public override nint RowsInSection (UITableView tableView, nint section)
		{
			return names.Length;
		}

		public override UITableViewCell GetCell (UITableView tableView, NSIndexPath indexPath)
		{
			string data = names [indexPath.Row];
			UITableViewCell cell = null;
			switch(indexPath.Row)
			{
			case 0:
				cell = new UITableViewCell (UITableViewCellStyle.Default, null);
				cell.Accessory = UITableViewCellAccessory.Checkmark;
				break;
			case 1:
				cell = new UITableViewCell (UITableViewCellStyle.Subtitle, null);
				cell.Accessory = UITableViewCellAccessory.DetailButton;
				break;
			case 2:
				cell = new UITableViewCell (UITableViewCellStyle.Value1, null);
				cell.Accessory = UITableViewCellAccessory.DetailDisclosureButton;
				break;
			case 3:
				cell = new UITableViewCell (UITableViewCellStyle.Value2, null);
				cell.Accessory = UITableViewCellAccessory.DisclosureIndicator;
				break;
			}

			cell.TextLabel.Text = data;

			if(cell.DetailTextLabel !=null)
				cell.DetailTextLabel.Text = "subtitle";
			
			return cell;
		}

		public override void AccessoryButtonTapped (UITableView tableView, NSIndexPath indexPath)
		{
			var controller = UIAlertController.Create("Accessory Details", 
				names [indexPath.Row], UIAlertControllerStyle.Alert);
			controller.AddAction(UIAlertAction.Create("OK", UIAlertActionStyle.Default, null));

			PresentViewController(controller, true, null);
		}


		public override void RowSelected (UITableView tableView, NSIndexPath indexPath)
		{
			var controller = UIAlertController.Create("Details", 
				names [indexPath.Row], UIAlertControllerStyle.Alert);
			controller.AddAction(UIAlertAction.Create("OK", UIAlertActionStyle.Default, null));

			PresentViewController(controller, true, null);
		}
	}
}
